import { forwardRef, useEffect, useState } from 'react';
import { AlertCircle, Check, ChevronDown, FileUp, X } from 'lucide-react';

export function Button({ variant = 'primary', size = 'md', className = '', loading = false, children, ...props }) { return <button className={`button button-${variant} button-${size} ${className}`} disabled={loading || props.disabled} {...props}>{loading && <span className="spinner"/>}{children}</button>; }
export function Card({ className = '', children, ...props }) { return <section className={`surface-card ${className}`} {...props}>{children}</section>; }
export function Badge({ tone = 'neutral', children }) { return <span className={`badge badge-${tone}`}>{children}</span>; }
export const Input = forwardRef(function Input({ label, error, hint, className = '', as = 'input', leadingIcon, ...props }, ref) { const Tag = as; return <label className="field"><span>{label}</span><span className={`field-wrap ${leadingIcon ? 'has-leading-icon' : ''}`}>{leadingIcon}<Tag ref={ref} className={`field-control ${error ? 'field-invalid' : ''} ${className}`} aria-invalid={!!error} {...props}/></span>{error ? <small className="field-error"><AlertCircle size={13}/>{error}</small> : hint ? <small className="field-hint">{hint}</small> : null}</label>; });
export function Skeleton({ className = '' }) { return <span className={`skeleton ${className}`} aria-hidden="true"/>; }
export function JobSkeleton() { return <Card className="job-skeleton"><div className="skeleton-row"><Skeleton className="skeleton-avatar"/><Skeleton className="skeleton-short"/></div><Skeleton className="skeleton-title"/><Skeleton className="skeleton-line"/><Skeleton className="skeleton-line small"/><Skeleton className="skeleton-foot"/></Card>; }
export function EmptyState({ icon: Icon = FileUp, title, description, action }) { return <div className="empty-state"><div className="empty-state-icon"><Icon size={24}/></div><h3>{title}</h3><p>{description}</p>{action}</div>; }
export function Modal({ open, onClose, title, description, children }) { useEffect(()=>{if(!open)return;const key=e=>{if(e.key==='Escape')onClose();};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[open,onClose]);if (!open) return null; return <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><section className="modal-card" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="icon-button modal-dismiss" onClick={onClose} aria-label="Close dialog"><X size={18}/></button><h2 id="modal-title">{title}</h2>{description && <p className="muted modal-description">{description}</p>}{children}</section></div>; }
export function Dropdown({ value, onChange, options, label }) { const [open, setOpen] = useState(false); return <div className="dropdown"><button className="dropdown-trigger" aria-label={label} aria-expanded={open} onClick={() => setOpen(!open)}>{options.find((o) => o.value === value)?.label || label}<ChevronDown size={15}/></button>{open && <div className="dropdown-menu">{options.map((o) => <button key={o.value} onClick={() => { onChange(o.value); setOpen(false); }}>{o.label}{o.value === value && <Check size={14}/>}</button>)}</div>}</div>; }
export function FileDropzone({ file, onChange, error }) { const [dragging, setDragging] = useState(false); const accept = (f) => f && onChange(f); return <div className={`file-dropzone ${dragging ? 'is-dragging' : ''} ${error ? 'field-invalid' : ''}`} onDragOver={(e) => { e.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(e) => { e.preventDefault(); setDragging(false); accept(e.dataTransfer.files?.[0]); }}><input type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={(e) => accept(e.target.files?.[0])} aria-label="Upload resume"/><div className="upload-icon"><FileUp size={20}/></div><strong>{file?.name || 'Drop your resume here'}</strong><span>{file ? `${(file.size / 1024 / 1024).toFixed(2)} MB · Click to replace` : 'or click to browse · PDF or DOCX · max 5 MB'}</span>{error && <small className="field-error">{error}</small>}</div>; }
