"use client";

import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowUpRight, BriefcaseBusiness, Building2, CalendarDays, Check, CircleDollarSign, MapPin, ShieldCheck } from "lucide-react";
import { ApplicationDialog } from "@/features/applications/components/application-dialog";
import ReactMarkdown from "react-markdown";
import { Button } from "@/components/ui/button";
import type { Job } from "@/types/domain";

export function JobDetail({ id }: { id: string }) {
  const router = useRouter();
  const [applyOpen, setApplyOpen] = useState(false);
  const query = useQuery({ queryKey: ["job", id], queryFn: async ({ signal }) => { const response = await fetch(`/api/v1/jobs/${encodeURIComponent(id)}`, { signal, headers: { Accept: "application/json" } }); if (!response.ok) throw new Error("This opportunity may have closed."); return response.json() as Promise<Job & { recruiterName?: string }>; }, enabled: /^\d+$/.test(id) });
  if (query.isPending) return <main className="page-shell detail-page"><div className="detail-skeleton" aria-label="Loading role details"><span/><span/><span/><span/></div></main>;
  if (query.isError || !query.data) return <main className="page-shell detail-page"><Link className="back-link" href="/jobs"><ArrowLeft size={15}/> All opportunities</Link><div className="empty-results"><h1>We couldn’t find that role.</h1><p>{query.error?.message ?? "The link may be out of date."}</p><Link className="button button-dark" href="/jobs">Browse open roles</Link></div></main>;
  const job = query.data;
  const quickApply = () => { if (!localStorage.getItem("token")) { router.push(`/login?next=${encodeURIComponent(`/jobs/${id}`)}`); return; } setApplyOpen(true); };
  return <><main className="page-shell detail-page"><Link className="back-link" href="/jobs"><ArrowLeft size={15}/> Back to opportunities</Link><div className="detail-layout"><article className="detail-content"><div className="detail-company"><span className="company-mark company-mark-large">{job.companyName.slice(0, 1).toUpperCase()}</span><span><strong>{job.companyName}</strong><small>{job.recruiterName ? `Hiring team · ${job.recruiterName}` : "Thoughtful team, hiring now"}</small></span><span className="verified-badge"><Check size={12}/> Hiring now</span></div><h1>{job.title}</h1><div className="detail-meta"><span><MapPin size={15}/>{job.location}</span><span><BriefcaseBusiness size={15}/>{job.jobType.replaceAll("_", " ").toLowerCase()}</span><span><CalendarDays size={15}/>{new Intl.DateTimeFormat("en", { month: "short", day: "numeric", year: "numeric" }).format(new Date(job.createdAt))}</span></div><div className="salary-transparency"><span className="salary-icon"><CircleDollarSign size={19}/></span><span><small>COMPENSATION</small><strong>{job.salaryRange || "Shared during the conversation"}</strong></span><span className="salary-pill">{job.salaryRange ? "Salary shared" : "Ask the team"}</span></div><div className="article-rule"/><section className="description-section"><h2>About this opportunity</h2><ReactMarkdown>{job.description || "Reach out to the team to learn more about this opportunity."}</ReactMarkdown></section><section className="company-overview"><div className="company-overview-icon"><Building2 size={19}/></div><div><span className="eyebrow">THE TEAM</span><h2>Get to know {job.companyName}</h2><p>Small, thoughtful teams do their best work together. Start a conversation and see if this could be your next chapter.</p></div></section></article><aside className="apply-card"><span className="eyebrow">READY WHEN YOU ARE</span><h2>Could this be your next?</h2><p>{job.externalApplyUrl ? "This team accepts applications on their careers site." : "Send your experience directly to the hiring team. It only takes a couple of minutes."}</p>{job.externalApplyUrl ? <a className="button button-dark full-width" href={job.externalApplyUrl} target="_blank" rel="noopener noreferrer">Continue to company site <ArrowUpRight size={16}/><span className="sr-only"> (opens in a new tab)</span></a> : <Button className="full-width" onClick={quickApply}>Quick apply <ArrowUpRight size={16}/></Button>}<div className="apply-divider"/><div className="apply-trust"><ShieldCheck size={16}/><span>Your application is only shared with {job.companyName}.</span></div><div className="apply-trust"><Check size={16}/><span>No account required to explore opportunities.</span></div></aside></div></main><ApplicationDialog job={job} onClose={() => setApplyOpen(false)}/></>;
}
