import { Link, NavLink, Outlet } from 'react-router-dom';
import { ArrowUpRight, BriefcaseBusiness, LogOut, Menu, Moon, Settings2, Sparkles, Sun } from 'lucide-react';
import { useState } from 'react';
import { useAuth } from '../context/AuthContext';

export function MainLayout() {
  const { user, logout, theme, toggleTheme } = useAuth(); const [open, setOpen] = useState(false);
  return <div className="app-shell"><header className="site-header"><Link to="/" className="wordmark"><span className="wordmark-icon">n</span> northstar<span className="wordmark-period">.</span></Link><button className="mobile-toggle icon-button" onClick={() => setOpen(!open)} aria-label="Toggle navigation"><Menu size={20}/></button><nav className={`site-nav ${open ? 'nav-open' : ''}`}><NavLink to="/jobs">Find a job</NavLink>{user?.role === 'RECRUITER' && <NavLink to="/recruiter">Recruiter studio</NavLink>}{user?.role === 'JOB_SEEKER' && <NavLink to="/dashboard">My applications</NavLink>}<span className="nav-grow"/><button className="icon-button theme-toggle" onClick={toggleTheme} aria-label="Toggle color theme">{theme === 'dark' ? <Sun size={17}/> : <Moon size={17}/>}</button>{user ? <><span className="nav-greeting">{user.firstName}</span><button className="header-link" onClick={logout}><LogOut size={15}/> Sign out</button></> : <><Link className="header-link" to="/login">Log in</Link><Link className="button button-primary button-sm" to="/register">Get started <ArrowUpRight size={15}/></Link></>}</nav></header><Outlet/><footer className="site-footer"><Link to="/" className="wordmark"><span className="wordmark-icon">n</span> northstar<span className="wordmark-period">.</span></Link><span>Work with intention. © 2026 Northstar.</span><Link to="/jobs">Explore opportunities <ArrowUpRight size={14}/></Link></footer></div>;
}
export function AuthLayout() { return <div className="auth-layout"><Link to="/" className="wordmark"><span className="wordmark-icon">n</span> northstar<span className="wordmark-period">.</span></Link><Outlet/><p className="auth-footer">Thoughtful work begins with a thoughtful next step.</p></div>; }
export function DashboardLayout() {
  const { user, logout, theme, toggleTheme } = useAuth(); const [open, setOpen] = useState(false); const recruiter = user?.role === 'RECRUITER' || user?.role === 'ADMIN';
  return <div className="dashboard-layout"><aside className={`dashboard-sidebar ${open ? 'sidebar-open' : ''}`}><Link to="/" className="wordmark"><span className="wordmark-icon">n</span> northstar<span className="wordmark-period">.</span></Link><div className="sidebar-caption">WORKSPACE</div><NavLink to={recruiter ? '/recruiter' : '/dashboard'} className="sidebar-link"><BriefcaseBusiness size={17}/>{recruiter ? 'Hiring overview' : 'My applications'}</NavLink><NavLink to="/jobs" className="sidebar-link"><Sparkles size={17}/>Discover roles</NavLink><NavLink to="/dashboard/profile" className="sidebar-link"><Settings2 size={17}/>Profile settings</NavLink><div className="sidebar-bottom"><div className="avatar-small">{user?.firstName?.[0]}{user?.lastName?.[0]}</div><div className="sidebar-user"><b>{user?.firstName} {user?.lastName}</b><small>{recruiter ? 'Recruiter' : 'Job seeker'}</small></div><button className="icon-button" onClick={toggleTheme} title={`Switch to ${theme==='dark'?'light':'dark'} theme`}>{theme==='dark'?<Sun size={16}/>:<Moon size={16}/>}</button><button className="icon-button" onClick={logout} title="Sign out"><LogOut size={16}/></button></div></aside><main className="dashboard-main"><header className="dashboard-mobilebar"><button className="icon-button" onClick={() => setOpen(!open)} aria-label="Open dashboard menu"><Menu/></button><Link to="/" className="wordmark"><span className="wordmark-icon">n</span> northstar.</Link></header><Outlet/></main>{open && <button className="sidebar-scrim" onClick={() => setOpen(false)} aria-label="Close menu"/>}</div>;
}
