import { Link } from 'react-router-dom';
import { ArrowUpRight, BriefcaseBusiness, CircleDashed, FileCheck2, Search, XCircle } from 'lucide-react';
import { useMyApplications } from '../services/queries';
import { Badge, Button, Card, EmptyState, Skeleton } from '../components/ui';

const statusTone = { APPLIED:'indigo', REVIEWING:'amber', SHORTLISTED:'green', REJECTED:'rose', HIRED:'green' };
const statusIcon = { APPLIED:CircleDashed, REVIEWING:CircleDashed, SHORTLISTED:FileCheck2, REJECTED:XCircle, HIRED:FileCheck2 };
function ApplicationRow({ item }) { const Icon=statusIcon[item.status]||CircleDashed; return <Card className="application-card"><div className="company-avatar">{item.companyName?.[0]}</div><div className="application-summary"><div className="application-title-row"><h3>{item.jobTitle}</h3><Badge tone={statusTone[item.status]||'neutral'}><Icon size={13}/>{item.status?.toLowerCase().replace('_',' ')}</Badge></div><p>{item.companyName} <span>·</span> Applied {new Intl.DateTimeFormat('en',{month:'short',day:'numeric',year:'numeric'}).format(new Date(item.appliedAt))}</p></div><Link className="application-open" to={`/jobs/${item.jobId}`} aria-label={`View ${item.jobTitle}`}><ArrowUpRight size={18}/></Link></Card>; }
export default function ApplicationTrackerPage() { const query=useMyApplications(); const apps=query.data||[]; const active=apps.filter(a=>!['REJECTED','HIRED'].includes(a.status)).length; return <div className="dash-content"><div className="dashboard-heading"><div><span className="eyebrow">YOUR JOB SEARCH</span><h1>Applications <em>in motion.</em></h1><p>Keep up with every opportunity you’ve raised your hand for.</p></div><Link to="/jobs"><Button variant="secondary"><Search size={16}/> Find more roles</Button></Link></div><div className="tracker-stats"><Card><span>In progress</span><b>{query.isLoading?<Skeleton className="stat-skeleton"/>:active}</b></Card><Card><span>Total applications</span><b>{query.isLoading?<Skeleton className="stat-skeleton"/>:apps.length}</b></Card><Card><span>Offers</span><b>{query.isLoading?<Skeleton className="stat-skeleton"/>:apps.filter(a=>a.status==='HIRED').length}</b></Card></div><div className="list-section-heading"><div><h2>Your applications</h2><span>{apps.length} total</span></div><BriefcaseBusiness size={18}/></div>{query.isLoading?<div className="application-list">{[1,2,3].map(i=><Card className="application-card" key={i}><Skeleton className="skeleton-avatar"/><div className="application-summary"><Skeleton className="skeleton-title"/><Skeleton className="skeleton-line small"/></div></Card>)}</div>:query.isError?<EmptyState title="Applications couldn’t load" description="Please check your connection and try again." action={<Button variant="secondary" onClick={()=>query.refetch()}>Try again</Button>}/>:apps.length?<div className="application-list">{apps.map(app=><ApplicationRow item={app} key={app.id}/>)}</div>:<EmptyState icon={BriefcaseBusiness} title="Your next opportunity starts here" description="Explore roles that feel right. Your applications and their progress will show up here." action={<Link to="/jobs"><Button>Explore open roles <ArrowUpRight size={16}/></Button></Link>}/>}</div>; }
