import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, HeartHandshake, MoveUpRight, Sparkles } from 'lucide-react';
import { useFeaturedJobs } from '../services/queries';
import { Button, Card, EmptyState, JobSkeleton } from '../components/ui';
import JobsPageCard from './JobsPageCard';

export default function HomePage() {
  const { data = [], isLoading } = useFeaturedJobs();
  return <><main><section className="home-hero"><div className="hero-copy"><div className="eyebrow"><Sparkles size={14}/> A MORE HUMAN WAY TO FIND WORK</div><h1>Make work<br/>mean <em>something.</em></h1><p>Find thoughtful teams, meaningful work, and your next good thing — all in one place.</p><div className="hero-buttons"><Link to="/jobs"><Button>Explore open roles <ArrowUpRight size={16}/></Button></Link><span>Good people. Better work.</span></div><div className="hero-proof"><div><b>1,200<span>+</span></b><small>open roles</small></div><i/><div><b>380<span>+</span></b><small>growing teams</small></div><i/><div><b>4.9<span>/5</span></b><small>candidate rating</small></div></div></div><div className="hero-visual"><div className="hero-visual-top"><span className="visual-spark">✳</span><span>Make room for what’s next</span></div><div className="visual-window"><div className="visual-dots"><i/><i/><i/></div><div className="visual-line w-50"/><div className="visual-line w-80"/><div className="visual-job"><span className="visual-company">f</span><div><b>Product Designer</b><small>Fieldwork Studio · Remote</small></div><MoveUpRight size={17}/></div><div className="visual-tags"><span>People-first</span><span>Flexible</span><span>Purposeful</span></div></div><div className="visual-sticker"><HeartHandshake size={18}/><span>Good work<br/>starts with people.</span></div><div className="visual-caption">YOUR NEXT CHAPTER IS CLOSER THAN YOU THINK</div></div></section><section className="featured-section"><div className="section-title"><div><span className="eyebrow">FRESH OPPORTUNITIES</span><h2>Good work, right this way<span className="accent-dot">.</span></h2><p>Roles from teams building with intention.</p></div><Link className="inline-link" to="/jobs">All open roles <ArrowRight size={16}/></Link></div>{isLoading?<div className="job-grid">{[1,2,3].map(x=><JobSkeleton key={x}/>)}</div>:data.length?<div className="job-grid">{data.slice(0,3).map(job=><JobsPageCard job={job} key={job.id}/>)}</div>:<EmptyState title="New opportunities are on their way" description="Check back soon, or browse all roles to see what’s open." action={<Link to="/jobs"><Button variant="secondary">Browse every role</Button></Link>}/>}</section><section className="recruiter-cta"><div><span className="eyebrow">FOR THOUGHTFUL TEAMS</span><h2>Build something good<br/>with good people.</h2><p>Meet candidates who care about the work and the why behind it.</p></div><Link to="/register?role=RECRUITER"><Button variant="light">Find your next teammate <ArrowUpRight size={16}/></Button></Link></section></main></>;
}
