import { useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowDownUp, ArrowRight, BriefcaseBusiness, MapPin, Search, SlidersHorizontal, X } from 'lucide-react';
import { useJobs } from '../services/queries';
import { Badge, Button, Card, EmptyState, Input, JobSkeleton } from '../components/ui';

function JobCard({ job }) { return <Link to={`/jobs/${job.id}`} className="job-card-link"><Card className="job-card"><div className="job-card-heading"><span className="company-avatar">{job.companyName?.[0]}</span><span className="job-company">{job.companyName}</span><span className="job-age">{new Intl.DateTimeFormat('en',{month:'short',day:'numeric'}).format(new Date(job.createdAt))}</span></div><h3>{job.title}</h3><div className="job-metadata"><span><MapPin size={14}/>{job.location}</span><span><BriefcaseBusiness size={14}/>{job.jobType?.replace('_',' ')}</span></div><div className="job-card-bottom"><span>{job.salaryRange || 'Compensation discussed'}</span><span className="job-arrow"><ArrowRight size={16}/></span></div></Card></Link>; }

export default function JobsPage() {
  const [params, setParams] = useSearchParams();
  const filters = useMemo(() => ({ keyword: params.get('keyword') || '', location: params.get('location') || '', jobType: params.get('jobType') || '', page: Number(params.get('page') || 0), size: 9, sort: 'createdAt,desc' }), [params]);
  const [draft, setDraft] = useState({ keyword: filters.keyword, location: filters.location, jobType: filters.jobType });
  const query = useJobs(filters); const page = query.data;
  const submit = (event) => { event.preventDefault(); const next = new URLSearchParams(); Object.entries(draft).forEach(([k,v]) => v && next.set(k,v)); next.set('page','0'); setParams(next); };
  const reset = () => { setDraft({keyword:'',location:'',jobType:''}); setParams({page:'0'}); };
  return <main className="content-wrap jobs-page"><div className="page-heading"><div><span className="eyebrow"><SlidersHorizontal size={14}/> THE OPPORTUNITY BOARD</span><h1>Find work that <em>fits.</em></h1><p>Explore teams who care about how the work gets done.</p></div><div className="result-note"><span className="result-dot"/> Curated opportunities</div></div>
    <Card className="filter-card"><form className="filters-form" onSubmit={submit}><Input label="Search" placeholder="Role, skill, or company" value={draft.keyword} onChange={e=>setDraft({...draft,keyword:e.target.value})} leadingIcon={<Search size={17}/>} /><Input label="Location" placeholder="City or remote" value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})} leadingIcon={<MapPin size={17}/>} /><label className="field"><span>Job type</span><select className="field-control" value={draft.jobType} onChange={e=>setDraft({...draft,jobType:e.target.value})}><option value="">All types</option><option value="FULL_TIME">Full time</option><option value="PART_TIME">Part time</option><option value="REMOTE">Remote</option></select></label><Button type="submit"><Search size={16}/> Search jobs</Button></form>{Object.values(draft).some(Boolean)&&<button className="clear-filters" onClick={reset}><X size={13}/> Clear filters</button>}</Card>
    <div className="list-toolbar"><p><strong>{page?.totalElements ?? '—'}</strong> roles to explore</p><span><ArrowDownUp size={14}/> Newest first</span></div>
    {query.isError ? <EmptyState icon={Search} title="We couldn't load roles" description={query.error?.response?.data?.error || 'Check your connection and try again.'} action={<Button variant="secondary" onClick={() => query.refetch()}>Try again</Button>}/> : query.isLoading ? <div className="job-grid">{Array.from({length:6},(_,i)=><JobSkeleton key={i}/>)}</div> : page?.content?.length ? <div className={`job-grid ${query.isFetching?'is-refreshing':''}`}>{page.content.map(job=><JobCard key={job.id} job={job}/>)}</div> : <EmptyState icon={Search} title="No roles match those filters" description="Try a broader search or clear your filters to see every opening." action={<Button variant="secondary" onClick={reset}>Clear all filters</Button>}/>}
    <div className="pagination"><Button variant="secondary" size="sm" disabled={filters.page===0} onClick={()=>setParams({...Object.fromEntries(params),page:String(filters.page-1)})}>Previous</Button><span>Page {filters.page+1} of {Math.max(page?.totalPages || 1,1)}</span><Button variant="secondary" size="sm" disabled={!page||filters.page+1>=page.totalPages} onClick={()=>setParams({...Object.fromEntries(params),page:String(filters.page+1)})}>Next</Button></div>
  </main>;
}
