import { useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { toast } from 'sonner';
import { BadgeCheck, UserRound } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { useProfile, useUpdateProfile } from '../services/queries';
import { profileSchema } from '../types/schemas';
import { Badge, Button, Card, Input, Skeleton } from '../components/ui';

export default function ProfilePage(){const profile=useProfile();const update=useUpdateProfile();const {user,updateUser}=useAuth();const form=useForm({resolver:zodResolver(profileSchema),defaultValues:{firstName:'',lastName:''}});useEffect(()=>{if(profile.data)form.reset({firstName:profile.data.firstName,lastName:profile.data.lastName});},[profile.data,form]);const submit=form.handleSubmit(values=>update.mutate(values,{onSuccess:data=>{updateUser(data);toast.success('Profile saved.');},onError:error=>toast.error(error.response?.data?.error||'Could not save your profile.')}));return <div className="dash-content"><div className="dashboard-heading"><div><span className="eyebrow">YOUR ACCOUNT</span><h1>Profile <em>details.</em></h1><p>Keep the basics up to date as you move forward.</p></div></div><Card className="profile-card"><div className="profile-card-heading"><span className="profile-avatar"><UserRound size={22}/></span><div><h2>Personal information</h2><p>This information is private to your account.</p></div><Badge tone="green"><BadgeCheck size={13}/>{user?.role?.replace('_',' ')}</Badge></div>{profile.isError?<p className="profile-error">Could not load your profile. Please refresh and try again.</p>:<form className="form-stack profile-form" onSubmit={submit} noValidate>{profile.isLoading?<><Skeleton className="skeleton-title"/><Skeleton className="skeleton-title"/></>:<><div className="form-two-col"><Input label="First name" error={form.formState.errors.firstName?.message} {...form.register('firstName')}/><Input label="Last name" error={form.formState.errors.lastName?.message} {...form.register('lastName')}/></div><Input label="Email address" value={profile.data?.email||user?.email||''} readOnly hint="Email address is managed by your sign-in."/></>}<div className="profile-submit"><Button type="submit" loading={update.isPending} disabled={profile.isLoading}>Save changes</Button></div></form>}</Card></div>;}
