import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { toast } from 'sonner';
import { ArrowUpRight, BriefcaseBusiness, ClipboardList, Plus, Users } from 'lucide-react';
import { useCreateJob, useRecruiterData, useUpdateApplicationStatus } from '../services/queries';
import { jobSchema } from '../types/schemas';
import { Badge, Button, Card, EmptyState, Input, Modal, Skeleton } from '../components/ui';

export default function RecruiterDashboardPage() {
  const [createOpen,setCreateOpen]=useState(false);const data=useRecruiterData();const jobs=data.jobs.data||[];const applications=data.applications.data||[];const create=useCreateJob();const update=useUpdateApplicationStatus();const form=useForm({resolver:zodResolver(jobSchema),defaultValues:{jobType:'FULL_TIME',salaryRange:''}});
  const submit=form.handleSubmit(values=>create.mutate(values,{onSuccess:()=>{setCreateOpen(false);form.reset();toast.success('Job posted successfully!');},onError:e=>toast.error(e.response?.data?.error||'Could not post this role.')}));
  const setStatus=(id,status)=>update.mutate({id,status},{onSuccess:()=>toast.success('Application status updated.'),onError:()=>toast.error('Could not update this applicant.')});
  return <div className="dash-content"><div className="dashboard-heading"><div><span className="eyebrow">RECRUITER WORKSPACE</span><h1>People make <em>the work.</em></h1><p>Your roles and the people ready to make an impact.</p></div><Button onClick={()=>setCreateOpen(true)}><Plus size={17}/> Post a role</Button></div>
    <div className="tracker-stats recruiter-stats">{[[BriefcaseBusiness,'Open roles',jobs.length,data.jobs.isLoading],[Users,'Applicants',applications.length,data.applications.isLoading],[ClipboardList,'Shortlisted',applications.filter(a=>a.status==='SHORTLISTED').length,data.applications.isLoading]].map(([Icon,label,value,loading])=><Card key={label}><span><Icon size={15}/>{label}</span><b>{loading?<Skeleton className="stat-skeleton"/>:value}</b></Card>)}</div>
    <div className="list-section-heading"><div><h2>Your open roles</h2><span>{jobs.length} published</span></div><BriefcaseBusiness size={18}/></div>{data.jobs.isLoading?<div className="application-list"><Skeleton className="skeleton-title"/></div>:jobs.length?<div className="application-list">{jobs.map(job=><Card className="recruiter-job-row" key={job.id}><span className="company-avatar">{job.companyName?.[0]}</span><div className="application-summary"><h3>{job.title}</h3><p>{job.companyName} · {job.location} · {job.jobType?.replace('_',' ')}</p></div><Badge tone="green">Live</Badge><a className="application-open" href={`/jobs/${job.id}`} target="_blank" rel="noreferrer"><ArrowUpRight size={17}/></a></Card>)}</div>:<EmptyState icon={BriefcaseBusiness} title="Your next great hire starts with a role" description="Publish an opportunity and meet thoughtful candidates." action={<Button onClick={()=>setCreateOpen(true)}><Plus size={16}/> Post your first role</Button>}/>}
    <div className="list-section-heading applicants-heading"><div><h2>Applicant pipeline</h2><span>Review and update candidate status</span></div><Users size={18}/></div>{data.applications.isLoading?<div className="application-list"><Skeleton className="skeleton-title"/></div>:applications.length?<div className="application-list recruiter-app-list">{applications.map(app=><Card className="recruiter-app-row" key={app.id}><span className="company-avatar">{app.applicantName?.[0]}</span><div className="application-summary"><h3>{app.applicantName}</h3><p>{app.jobTitle} · {app.applicantEmail}</p><a href={app.resumeUrl} className="resume-action" target="_blank" rel="noreferrer">Open resume ↗</a></div><select aria-label={`Status for ${app.applicantName}`} className="status-select" value={app.status} disabled={update.isPending} onChange={e=>setStatus(app.id,e.target.value)}>{['APPLIED','REVIEWING','SHORTLISTED','REJECTED','HIRED'].map(s=><option key={s} value={s}>{s.replace('_',' ')}</option>)}</select></Card>)}</div>:<EmptyState icon={Users} title="Your pipeline is ready when you are" description="When people apply to one of your roles, you’ll be able to review them here."/>}
    <Modal open={createOpen} onClose={()=>!create.isPending&&setCreateOpen(false)} title="Post an opportunity" description="Share the role with people who care about doing thoughtful work."><form className="form-stack" onSubmit={submit} noValidate><Input label="Job title" placeholder="Senior Product Designer" error={form.formState.errors.title?.message} {...form.register('title')}/><div className="form-two-col"><Input label="Company" placeholder="Fieldwork Studio" error={form.formState.errors.companyName?.message} {...form.register('companyName')}/><Input label="Location" placeholder="Remote / New York" error={form.formState.errors.location?.message} {...form.register('location')}/></div><div className="form-two-col"><label className="field"><span>Job type</span><select className="field-control" {...form.register('jobType')}><option value="FULL_TIME">Full time</option><option value="PART_TIME">Part time</option><option value="REMOTE">Remote</option></select></label><Input label="Salary range" placeholder="$90k – $120k" error={form.formState.errors.salaryRange?.message} {...form.register('salaryRange')}/></div><Input as="textarea" rows="6" label="Description" placeholder="What will this person do? What makes your team a great place to work?" error={form.formState.errors.description?.message} {...form.register('description')}/><Button type="submit" className="full-width" loading={create.isPending}>Publish role <ArrowUpRight size={16}/></Button></form></Modal>
  </div>;
}
